export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const MESSAGES_LIST = 'MESSAGES_LIST';
export const ADD_USER = 'ADD_USER';
export const USERS_LIST = 'USERS_LIST';
export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SHOW_MESSAGES = 'SHOW_MESSAGES';
export const REQUEST_CONTROLLERS = 'REQUEST_CONTOLLERS';
export const RECIEVE_CONTROLLERS = 'RECIEVE_CONTROLLERS';
export const ERROR_CONTROLLERS = 'ERROR_CONTROLLERS';
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const REQUEST_MESSAGES_SUCCESS = 'REQUEST_MESSAGES_SUCCESS';
export const REQUEST_MESSAGES_FAILURE = 'REQUEST_MESSAGES_FAILURE';
export const LOAD_CONTROLLERS_LIST = 'LOAD_CONTROLLERS_LIST';

export const FETCH_CONTROLLERS_SUCCEEDED = 'FETCH_CONTROLLERS_SUCCEEDED';
export const FETCH_CONTROLLERS_ERROR = 'FETCH_CONTROLLERS_ERROR';

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const LISTEN_MESSAGES = 'LISTEN_MESSAGES';
export const LISTEN_MESSAGE_SUCCESS = 'LISTEN_MESSAGE_SUCCESS';
export const LISTEN_MESSAGES_ERROR = 'LISTEN_MESSAGES_ERROR';