export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const MESSAGES_LIST = 'MESSAGES_LIST';
export const ADD_USER = 'ADD_USER';
export const USERS_LIST = 'USERS_LIST';
export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SHOW_MESSAGES = 'SHOW_MESSAGES';
export const REQUEST_CONTROLLERS = 'REQUEST_CONTOLLERS';
export const RECIEVE_CONTROLLERS = 'RECIEVE_CONTROLLERS';
export const ERROR_CONTROLLERS = 'ERROR_CONTROLLERS';
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const REQUEST_MESSAGES_SUCCESS = 'REQUEST_MESSAGES_SUCCESS';
export const REQUEST_MESSAGES_FAILURE = 'REQUEST_MESSAGES_FAILURE';

